[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " NERDTreeを表示/非表示
  nmap <silent> <Space>ne :NERDTreeToggle<CR>
  " 起動時にブックマークを表示
  let g:NERDTreeShowBookmarks=1
  " 選択しているファイルをブックマークに登録
  nmap <silent> <Space>a :<C-u>Bookmark<CR>
  " 選択しているファイルをブックマークから削除
  nmap <silent> <Space>d :<C-u>ClearBookmarks<CR>
  " 全ブックマークを削除
  nmap <silent> <Space>da :<C-u>ClearAllBookmarks<CR>
  " 隠しファイルを表示
  let g:NERDTreeShowHidden=1
  " 非表示ファイル
  let g:NERDTreeIgnore=['\.swp$', '.DS_Store']
  " 開いているウィンドウがNERDTreeだけならVimを閉じる
  autocmd Bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

#インストール方法メモ
#1. https://github.com/ryanoasis/nerd-fonts#font-installation のoption4: Homebrewでフォントをインストールする.
#2. 利用しているターミナルのフォントを手順1でインストールしたFontに変更する.iTerm2なら設定画面>Profiles>Text>Font>Change Fontから設定する.
#3. ryanoasis/vim-deviconsをインストールする.
[[plugins]] # 有名どころのVimプラグインにアイコンを追加する.
repo = 'ryanoasis/vim-devicons'

[[plugins]] # カラースキームを設定
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  " TODO: nestedについて&auとautocmdの違いについて
  autocmd MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]] # ステータスラインのテーマ
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
let g:airline_theme = 'light'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # カーソル位置のコンテキストに合わせて filetype を切り替え.
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストの filetype を判定するライブラリ.
repo = 'Shougo/context_filetype.vim'

[[plugins]] # Vimスクリプト基礎文法最速マスター( https://thinca.hatenablog.com/entry/20100201/1265009821 )を:help learn-vimscript で閲覧できる.
repo = 'mattn/learn-vimscript'

[[plugins]] # syntaxのチェック
repo =  'scrooloose/syntastic'
hook_add = '''
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_mode_map = { 'mode': 'active',
  \ 'active_filetypes': [],
  \ 'passive_filetypes': ['html'] }
'''

[[plugins]] # インデントを可視化.
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '¦'
'''

[[plugins]] # ウィンドウサイズを変更.
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<Space>w'
" enter で完了する.
let g:winresizer_keycode_finish = 13
'''

 [[plugins]] # コメントアウト.
repo = 'tyru/caw.vim'
