[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " NERDTreeを表示/非表示
  nmap <silent> <Space>ne :NERDTreeToggle<CR>
  " 起動時にブックマークを表示
  let g:NERDTreeShowBookmarks=1
  " 選択しているファイルをブックマークに登録
  nmap <silent> <Space>a :<C-u>Bookmark<CR>
  " 選択しているファイルをブックマークから削除
  nmap <silent> <Space>d :<C-u>ClearBookmarks<CR>
  " 全ブックマークを削除
  nmap <silent> <Space>da :<C-u>ClearAllBookmarks<CR>
  " 隠しファイルを表示
  let g:NERDTreeShowHidden=1
  " 非表示ファイル
  let g:NERDTreeIgnore=['\.swp$', '.DS_Store']
  " 開いているウィンドウがNERDTreeだけならVimを閉じる
  autocmd Bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

#インストール方法メモ
#1. https://github.com/ryanoasis/nerd-fonts#font-installation のoption4: Homebrewでフォントをインストールする.
#2. 利用しているターミナルのフォントを手順1でインストールしたFontに変更する.iTerm2なら設定画面>Profiles>Text>Font>Change Fontから設定する.
#3. ryanoasis/vim-deviconsをインストールする.
[[plugins]] # 有名どころのVimプラグインにアイコンを追加する.
repo = 'ryanoasis/vim-devicons'

[[plugins]] # カラースキームを設定
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  " TODO: nestedについて&auとautocmdの違いについて
  autocmd MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]] # ステータスラインのテーマ
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
let g:airline_theme = 'light'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
